version: "3"
services:
  oxo:
    image: ghcr.io/giftzwerg02/oxo:latest
    init: true
    environment:
      - DISCORD_TOKEN_FILE=/run/secrets/discord_token
    secrets:
      - discord_token
    labels:
      oxo.autoupdate: "true"
  shepherd:
    image: mazzolino/shepherd
    environment:
      SLEEP_TIME: "10s"
      IMAGE_AUTOCLEAN_LIMIT: "5"
      FILTER_SERVICES: "label=oxo.autoupdate"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
        - node.role == manager

secrets:
  discord_token:
    external: true