name: Build Docker Image
on:
  workflow_dispatch:
  push:
    branches:
      - staging

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: latest
  IMAGE_ARCHS: linux/amd64, linux/arm64

jobs:
  docker_build:
    name: Build and Push Image
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ IMAGE_ARCHS }}

      - name: Build Image
        run: |
          docker buildx build \
          --tag ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          --platform ${{ env.IMAGE_ARCHS }} .
            
      - name: Push To Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAG }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
