name: Build Docker Image
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - staging

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_ARCHS: linux/amd64

jobs:
  docker_build:
    name: Build and Push Image
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: ${{ env.IMAGE_ARCHS }}

      - name: Determine Image Name and Tag
        run: |
          name="${GITHUB_REPOSITORY,,}"
          echo "IMAGE_NAME=$name" >>${GITHUB_ENV}
          tag="${{ github.release.tag_name }}"
          if [ -z "$tag" ]; then tag="latest"; fi
          echo "IMAGE_TAG=$tag" >>${GITHUB_ENV}
          echo "Image: ${name}:${tag}"

      - name: Login to Container Repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Image
        run: |
          docker buildx build \
          --tag ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          --platform ${{ env.IMAGE_ARCHS }} .
      
      - name: Push To Container Repository
        run: |
          docker push ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
